// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fcijiacfcwzheyxuobtd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZjaWppYWNmY3d6aGV5eHVvYnRkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MzgyNzcsImV4cCI6MjA2NDMxNDI3N30.JM8hUbsX0Q6c1dUUjDW_NjOzhcQMhF3e2MphHrj-M4k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);